---

- name: NETDATA REDHAT | Install prerequisites packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - zlib-devel
    - libuuid-devel
    - libmnl-devel
    - gcc
    - make
    - git
    - autoconf
    - autogen
    - automake
    - pkgconfig
    - curl
    # - jq
    # - nodejs
