---

###
# NETDATA
###

# Version
netdata_version: v1.11.1

# Sources
netdata_source_url: https://github.com/netdata/netdata
netdata_source_path: /opt/netdata

# User
netdata_user: netdata

# Socket
netdata_bind_socket: "{{ hostvars[inventory_hostname].ip | default('127.0.0.1') }}"
